version: '3.9'
services:
    web:
        build: src
        container_name: ${APP_NAME:-music_php_web}
        depends_on:
            - db
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - ./src:/var/www/html
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${DB_NAME:-musicdb}
            - MYSQL_USER=${DB_USER:-musicphpapp}
            - MYSQL_PASSWORD=${DB_PASSWORD:?No password set}
        ports:
            - ${DB_PORT:-3306}:3306
