version: '3.9'
services:
    web:
        build: src
        env_file:
            - .env
            - ../.env
        environment:
            - DB_HOST=host.docker.internal
        depends_on:
            - db
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - ./src:/var/www/html
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS:?No password set}
            - MYSQL_DATABASE=${DB_NAME:-musicdb}
            - MYSQL_USER=${DB_USER:-musicphpapp}
            - MYSQL_PASSWORD=${DB_PASS:?No password set}
        ports:
            - ${DB_PORT:-3306}:3306
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
